spring:
  datasource:
#    url: jdbc:mysql://mysql.goormthon-6.svc.cluster.local:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    url: jdbc:mysql://127.0.0.1:13306/mydb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: myuser
    password: mypass123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

kakao:
  rest-key: 8c51fcbd7585e8f91d3eab8acdcccc5c   # REST API 키
  redirect: https://127.0.0.1:8080/login/kakao/callback # 인가 코드 콜백 UR

jwt:
  secret: aowifej2934ruvn0a9wenfc0a9wne
  expiry-seconds: 3600