spring:
  datasource:
    url: jdbc:mysql://mysql.goormthon-6.svc.cluster.local:3306/mydb
    username: myuser
    password: mypass123
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.zaxxer.hikari: DEBUG        # HikariCP ??? ? ??
    org.springframework.jdbc: DEBUG  # Spring JDBC
  jpa:
    hibernate:
      ddl-auto: none      # ??? update/create ?
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect